-- PERFILES ========================================================================================

insert into cap.dbo.seg_perfil values
('SUPER','SUPER USUARIO.-','Activo'),
('PAI','Acceso al modulo de seguridad del sistema','Activo'),
('Analista programador','Analista programador de sistemas','Activo'),
('Responsable de sistemas','Responsable de sistemas','Activo'),
('Responsable GCTI','Responsable de gestión de TI','Activo'),
('RyT','Redes y tecnologia','Activo'),
('Responsable R. y T.','Responsable de Redes y Tecnologia','Activo')

insert into [dbo].[log_actividad]
select 'SCRIPT','seg_perfil','CREACION', id, GETDATE() from [dbo].seg_perfil order by id

-- USUARIOS ========================================================================================

insert into cap.dbo.seg_usuario values
('01601','Codino Maria Eugenia',4,'Activo'),
('01969','Leon Lucas',3,'Activo'),
('01560','Denezio Sebastian',3,'Activo'),
('01702','Alvarado Belen',3,'Activo'),
('01570','Diaz Susana',3,'Activo'),
('01879','Cohan Gustavo',3,'Activo'),
('07501','Farinola Santiago',3,'Activo'),
('07488','Salazar Malcom',3,'Activo'),
('07489','Marquez Emanuel',3,'Activo'),
('07486','Gonzalez Fabricio',3,'Activo'),
('01704','Ojeda Ulises',7,'Activo'),
('01983','Oyarzun Ezequiel',6,'Activo'),
('01653','Gomez Patricio',6,'Activo'),
('01952','Alvarez Pablo',6,'Activo'),
('02004','Diaz Pastrana Martin',6,'Activo'),
('01547','Corbett Carlos',5,'Activo'),
('01655','Coraccio Alejandro',1,'Activo'),
('01896','Strazanec Oscar',2,'Activo'),
('01982','Olmos Corsini Franco',2,'Activo')

insert into [dbo].[log_actividad]
select 'SCRIPT','seg_usuario','CREACION', id, GETDATE() from [dbo].seg_usuario order by id


-- PERMISOS =========================================================================================

insert into cap.dbo.seg_permiso values 
('Actividades',1,0,''),
('Aplicaciones',1,0,''),
('Auxiliares',1,0,''),
('Bases',1,0,''),
('Comunicaciones',1,0,''),
('Dependencias',1,0,''),
('Firewalls',1,0,''),
('Gerencias',1,0,''),
('Hardwares',1,0,''),
('Herramientas',1,0,''),
('Instalaciones',1,0,''),
('Inventarios',1,0,''),
('Lenguajes',1,0,''),
('Perfiles',1,0,''),
('Permisos',1,0,''),
('Personal',1,0,''),
('Plataformas',1,0,''),
('Procesamientos',1,0,''),
('Proveedores',1,0,''),
('Reportes',1,0,''),
('Servicios',1,0,''),
('Servidores',1,0,''),
('Sitios',1,0,''),
('Switchs',1,0,''),
('Usuarios',1,0,''),
('Utilidades',1,0,''),
('Ver log',2,1,'actividades/vistas/FBuscarActividad'),
('Buscar',2,2,'aplicaciones/vistas/FBuscarPPAplicacion'),
('Buscar',2,2,'aplicaciones/vistas/FBuscarSPAplicacion'),
('Buscar',2,2,'aplicaciones/vistas/FBuscarTPAplicacion'),
('Aplicaciones',2,2,'aplicaciones/vistas/FConsultarAplicacion'),
('Crear',2,2,'aplicaciones/vistas/FCrearAplicacion'),
('Buscar',2,3,'auxiliares/vistas/FBuscarElementoAuxiliar'),
('Auxiliares',2,3,'auxiliares/vistas/FConsultarElementoAuxiliar'),
('Crear',2,3,'auxiliares/vistas/FCrearElementoAuxiliar'),
('Buscar base',2,4,'bases/vistas/FBuscarBase'),
('Buscar columna',2,4,'bases/vistas/FBuscarCampo'),
('Buscar SP',2,4,'bases/vistas/FBuscarProcedimiento'),
('Buscar tabla',2,4,'bases/vistas/FBuscarTabla'),
('Buscar vista',2,4,'bases/vistas/FBuscarVista'),
('Bases de datos',2,4,'bases/vistas/FConsultarBase'),
('Buscar',2,5,'comunicaciones/vistas/FBuscarComunicacion'),
('Comunicaciones',2,5,'comunicaciones/vistas/FConsultarComunicacion'),
('Crear',2,5,'comunicaciones/vistas/FCrearComunicacion'),
('Buscar hijo',2,6,'dependencias/vistas/FBuscarActivoHijo'),
('Buscar padre',2,6,'dependencias/vistas/FBuscarActivoPadre'),
('Crear hijo',2,6,'dependencias/vistas/FCrearActivoHijo'),
('Crear padre',2,6,'dependencias/vistas/FCrearActivoPadre'),
('Buscar',2,7,'firewalls/vistas/FBuscarFirewall'),
('Firewall',2,7,'firewalls/vistas/FConsultarFirewall'),
('Crear',2,7,'firewalls/vistas/FCrearFirewall'),
('Buscar depto',2,8,'gerencias/vistas/FBuscarDepartamento'),
('Buscar empleado',2,8,'gerencias/vistas/FBuscarEmpleado'),
('Buscar gerencia',2,8,'gerencias/vistas/FBuscarGerencia'),
('Crear depto',2,8,'gerencias/vistas/FCrearDepartamento'),
('Crear empleado',2,8,'gerencias/vistas/FCrearEmpleado'),
('Crear gerencia',2,8,'gerencias/vistas/FCrearGerencia'),
('Gerencias',2,20,'gerencias/vistas/FReporteGerencia'),
('Buscar',2,9,'hardwares/vistas/FBuscarHardware'),
('Hardwares',2,9,'hardwares/vistas/FConsultarHardware'),
('Crear',2,9,'hardwares/vistas/FCrearHardware'),
('Buscar',2,10,'herramientas/vistas/FBuscarHerramienta'),
('Consultar',2,10,'herramientas/vistas/FConsultarHerramienta'),
('Crear',2,10,'herramientas/vistas/FCrearHerramienta'),
('Buscar',2,11,'instalaciones/vistas/FBuscarInstalacion'),
('Instalaciones',2,11,'instalaciones/vistas/FConsultarInstalacion'),
('Crear',2,11,'instalaciones/vistas/FCrearInstalacion'),
('Ver historico',2,12,'inventarios/vistas/FConsultarHistorico'),
('Buscar',2,13,'lenguajes/vistas/FBuscarLenguaje'),
('Ver',2,13,'lenguajes/vistas/FConsultarLenguaje'),
('Crear',2,13,'lenguajes/vistas/FCrearLenguaje'),
('Buscar',2,14,'perfiles/vistas/FBuscarPerfil'),
('Crear',2,14,'perfiles/vistas/FCrearPerfil'),
('Buscar',2,15,'permisos/vistas/FBuscarPermiso'),
('Crear',2,15,'permisos/vistas/FCrearPermiso'),
('Buscar',2,16,'personales/vistas/FBuscarPersonal'),
('Personales',2,16,'personales/vistas/FConsultarPersonal'),
('Crear',2,16,'personales/vistas/FCrearPersonal'),
('Buscar',2,17,'plataformas/vistas/FBuscarPlataformaSO'),
('Crear',2,17,'plataformas/vistas/FCrearPlataformaSO'),
('Buscar lugar',2,18,'procesamientos/vistas/FBuscarLugarProcesamiento'),
('Buscar modo',2,18,'procesamientos/vistas/FBuscarModoProcesamiento'),
('Crear lugar',2,18,'procesamientos/vistas/FCrearLugarProcesamiento'),
('Crear modo',2,18,'procesamientos/vistas/FCrearModoProcesamiento'),
('Buscar proveedor',2,19,'proveedores/vistas/FBuscarProveedor'),
('Buscar responsable',2,19,'proveedores/vistas/FBuscarResponsable'),
('Ver proveedor',2,19,'proveedores/vistas/FConsultarProveedor'),
('Ver responsable',2,19,'proveedores/vistas/FConsultarResponsable'),
('Crear proveedor',2,19,'proveedores/vistas/FCrearProveedor'),
('Crear responsable',2,19,'proveedores/vistas/FCrearResponsable'),
('Buscar',2,21,'servicios/vistas/FBuscarServicio'),
('Crear',2,21,'servicios/vistas/FCrearServicio'),
('Buscar',2,22,'servidores/vistas/FBuscarServidor'),
('Consultar job',2,22,'servidores/vistas/FConsultarJob'),
('Consultar',2,22,'servidores/vistas/FConsultarServidor'),
('Crear',2,22,'servidores/vistas/FCrearServidor'),
('Servidores',2,20,'servidores/vistas/FReporteServidor'),
('Buscar sitio',2,23,'sitios/vistas/FBuscarSitio'),
('Crear sitio',2,23,'sitios/vistas/FCrearSitio'),
('Sitios',2,20,'sitios/vistas/FReporteSitio'),
('Buscar',2,24,'switches/vistas/FBuscarSwitch'),
('Switchs',2,24,'switches/vistas/FConsultarSwitch'),
('Crear',2,24,'switches/vistas/FCrearSwitch'),
('Buscar',2,25,'usuarios/vistas/FBuscarUsuario'),
('Crear',2,25,'usuarios/vistas/FCrearUsuario'),
('Conversor fecha',2,26,'utilidades/vistas/FConvertirFechas'),
('Encriptador',2,26,'utilidades/vistas/FEncriptador')

insert into [dbo].[log_actividad]
select 'SCRIPT','seg_usuario','CREACION', id, GETDATE() from [dbo].seg_permiso order by id

-- RELACION PERMISOS-PERFILES ======================================================================

insert into [dbo].[seg_perfil_permiso] values
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10),
(1,11),
(1,12),
(1,13),
(1,14),
(1,15),
(1,16),
(1,17),
(1,18),
(1,19),
(1,20),
(1,21),
(1,22),
(1,23),
(1,24),
(1,25),
(1,26),
(1,27),
(1,28),
(1,29),
(1,30),
(1,31),
(1,32),
(1,33),
(1,34),
(1,35),
(1,36),
(1,37),
(1,38),
(1,39),
(1,40),
(1,41),
(1,42),
(1,43),
(1,44),
(1,45),
(1,46),
(1,47),
(1,48),
(1,49),
(1,50),
(1,51),
(1,52),
(1,53),
(1,54),
(1,55),
(1,56),
(1,57),
(1,58),
(1,59),
(1,60),
(1,61),
(1,62),
(1,63),
(1,64),
(1,65),
(1,66),
(1,67),
(1,68),
(1,69),
(1,70),
(1,71),
(1,72),
(1,73),
(1,74),
(1,75),
(1,76),
(1,77),
(1,78),
(1,79),
(1,80),
(1,81),
(1,82),
(1,83),
(1,84),
(1,85),
(1,86),
(1,87),
(1,88),
(1,89),
(1,90),
(1,91),
(1,92),
(1,93),
(1,94),
(1,95),
(1,96),
(1,97),
(1,98),
(1,99),
(1,100),
(1,101),
(1,102),
(1,103),
(1,104),
(1,105),
(1,106),
(1,107),
(2,2),
(2,14),
(2,15),
(2,25),
(2,26),
(2,30),
(2,72),
(2,73),
(2,74),
(2,75),
(2,104),
(2,105),
(2,107),
(3,2),
(3,4),
(3,10),
(3,13),
(3,19),
(3,22),
(3,26),
(3,28),
(3,32),
(3,36),
(3,37),
(3,38),
(3,39),
(3,40),
(3,63),
(3,70),
(3,87),
(3,88),
(3,94),
(3,95),
(3,106),
(3,107),
(4,1),
(4,4),
(4,10),
(4,13),
(4,19),
(4,20),
(4,22),
(4,26),
(4,27),
(4,28),
(4,32),
(4,36),
(4,37),
(4,38),
(4,39),
(4,40),
(4,58),
(4,63),
(4,69),
(4,71),
(4,87),
(4,88),
(4,94),
(4,95),
(4,97),
(4,100),
(4,106),
(4,107),
(5,6),
(5,8),
(5,10),
(5,12),
(5,16),
(5,17),
(5,18),
(5,19),
(5,20),
(5,21),
(5,23),
(5,31),
(5,34),
(5,41),
(5,43),
(5,45),
(5,46),
(5,47),
(5,48),
(5,50),
(5,52),
(5,53),
(5,54),
(5,55),
(5,56),
(5,57),
(5,58),
(5,60),
(5,62),
(5,63),
(5,64),
(5,66),
(5,68),
(5,76),
(5,77),
(5,78),
(5,81),
(5,82),
(5,83),
(5,84),
(5,85),
(5,86),
(5,89),
(5,90),
(5,91),
(5,92),
(5,97),
(5,98),
(5,99),
(5,100),
(5,102),
(6,2),
(6,3),
(6,4),
(6,5),
(6,7),
(6,9),
(6,11),
(6,22),
(6,24),
(6,29),
(6,33),
(6,35),
(6,41),
(6,42),
(6,44),
(6,49),
(6,51),
(6,59),
(6,61),
(6,65),
(6,67),
(6,93),
(6,94),
(6,96),
(6,101),
(6,103),
(7,1),
(7,2),
(7,3),
(7,4),
(7,5),
(7,7),
(7,9),
(7,11),
(7,20),
(7,22),
(7,24),
(7,27),
(7,29),
(7,33),
(7,35),
(7,41),
(7,42),
(7,44),
(7,49),
(7,51),
(7,58),
(7,59),
(7,61),
(7,65),
(7,67),
(7,93),
(7,94),
(7,96),
(7,97),
(7,100),
(7,101),
(7,103)

-- MODOS DE PROCESAMIENTO ===========================================================================

insert into cap.dbo.psa_modo values
('On-line', 'Activo'),
('Batch', 'Activo'),
('Tiempo real', 'Activo'),
('Paralelo', 'Activo'),
('Distribuido', 'Activo')

insert into [dbo].[log_actividad]
select 'SCRIPT','psa_modo','CREACION', id, GETDATE() from [dbo].[psa_modo] order by id

-- LUGARES DE PROCESAMIENTO ==========================================================================

insert into [dbo].[psa_lugar] values
('Entidad','Activo'),
('Tercero - Local','Activo'),
('Tercero - Exterior','Activo')

insert into [dbo].[log_actividad]
select 'SCRIPT','psa_lugar','CREACION', id, GETDATE() from [dbo].[psa_lugar] order by id

-- PLATAFORMAS DE SISTEMA OPERATIVO ===================================================================

insert into [dbo].[pla_plataformaSO] values
('Windows Server','Activa'),
('Unix','Activa'),
('Linux','Activa'),
('DOS','Activa'),
('BSD','Activa'),
('Solaris','Activa'),
('Mac','Activa'),
('Propietaria','Activa')

insert into [dbo].[log_actividad]
select 'SCRIPT','pla_plataformaSO','CREACION', id, GETDATE() from [dbo].[pla_plataformaSO] order by id

-- SITIOS ==============================================================================================

insert into [dbo].[sit_sitio] values
('CPP1','CPD','Centro de Procesamiento Principal 1','San Juan','San Juan',5402,'Av. J. Ignacio de la Roza 85','Tercerizado', 'Activo'),
('CPP2','CPD','Centro de Procesamiento Principal 2','Santa Cruz','Río Gallegos',9400,'Av. Presidente Néstor C. Kirchner Nº812','Propio', 'Activo'),
('CPA1','CPD','Centro de Procesamiento Alternativo 1','Entre Ríos','Parana',3100,'Monte Casero Nº128','Tercerizado', 'Activo'),
('CPA2','CPD','Centro de Procesamiento Alternativo 2','Santa Cruz','Río Gallegos',9400,'Perito Moreno 157','Propio', 'Activo'),
('URP1','SAR','Sitio de Resguardo Principal 1','San Juan','San Juan',5402,'Av. J. Ignacio de la Roza 85','Tercerizado', 'Activo'),
('URP2','SAR','Sitio de Resguardo Principal 2','Santa Cruz','Río Gallegos',9400,'Av. Presidente Néstor C. Kirchner Nº812','Propio', 'Activo'),
('URS1','SAR','Sitio de Resguardo Secundario 1','San Juan','Caucete',5442,'Sarmiento esquina Laprida','Tercerizado', 'Activo'),
('URS2','SAR','Sitio de Resguardo Secundario 2','Santa Cruz','Río Gallegos',9400,'Perito Moreno 157','Propio', 'Activo'),
('01','SUC','Rio Gallegos','Santa Cruz','Rio Gallegos',9400,'Av.Pte Nestor Kirchner N° 812','Propio', 'Activo'),
('05','SUC','Buenos Aires','Buenos Aires','Buenos Aires',1001,'Suipacha 1065','Propio', 'Activo'),
('10','SUC','Caleta Olivia','Santa Cruz','Caleta Olivia',9011,'Avda. Independencia N° 1070','Propio', 'Activo'),
('15','SUC','Rio Turbio','Santa Cruz','Rio Turbio',9407,'Gobernador Lista N° 222','Propio', 'Activo'),
('20','SUC','Piedra Buena','Santa Cruz','Piedra Buena',9303,'Av.Gregorio Ibañez N° 168','Propio', 'Activo'),
('25','SUC','El Calafate','Santa Cruz','El Calafate',9405,'Avda. Del Libertador N° 1285','Propio', 'Activo'),
('30','SUC','Gobernador Gregores','Santa Cruz','Gobernador Gregores',9311,'Avda. San Martin N° 402','Propio', 'Activo'),
('40','SUC','Perito Moreno','Santa Cruz','Perito Moreno',9040,'Avda San Martin 1493','Propio', 'Activo'),
('41','SUC','Los Antiguos','Santa Cruz','Los Antiguos',9041,'Avda. 11 De Julio N° 531','Propio', 'Activo'),
('45','SUC','Las Heras','Santa Cruz','Las Heras',9017,'Antiguos Pobladores N°418','Propio', 'Activo'),
('50','SUC','Pico Truncado','Santa Cruz','Pico Truncado',9015,'Hipolito Irigoyen Y 9 De Julio','Propio', 'Activo'),
('55','SUC','Puerto Deseado','Santa Cruz','Puerto Deseado',9050,'San Martin N° 1056','Propio', 'Activo'),
('60','SUC','San Julian','Santa Cruz','San Julian',9310,'Av.San Martin N° 595','Propio', 'Activo'),
('70','SUC','Santa Cruz','Santa Cruz','Santa Cruz',9300,'Av.Piedra Buena N° 298','Propio', 'Activo'),
('75','SUC','Agencia Numero 1','Santa Cruz','Rio Gallegos',9400,'Perito Moreno 157','Propio', 'Activo'),
('80','SUC','Comodoro Rivadavia','Chubut','Comodoro Rivadavia',9000,'Avda. San Martin N° 175','Propio', 'Activo'),
('85','SUC','28 De Noviembre','Santa Cruz','28 De Noviembre',9407,'Antartida Argentina N° 427','Propio', 'Activo'),
('95','SUC','Casa Central','Santa Cruz','Casa Central',9400,'Av  Pte Nestor Kirchner N° 812','Propio', 'Activo')

insert into [dbo].[log_actividad]
select 'SCRIPT','sit_sitio','CREACION', id, GETDATE() from [dbo].[sit_sitio] order by id